/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculation_solitaire.PlayCardWindow;
import calculation_solitaire.WastePile;
import calculation_solitaire.Card;
import calculation_solitaire.FoundationPile;
import calculation_solitaire.Suit;
import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author Steven
 */
public class WinTest extends javax.swing.JFrame {

    /**
     * Creates new form WinTest
     */
    public WinTest() {
        this.funpile = new int[]{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 12, 13};
        funpile1=new FoundationPile(funpile);
        funpile1.setI(11);
        this.funpile = new int[]{2, 4, 6, 8, 10, 12, 1, 3, 5, 7, 9, 11, 13};
        funpile2=new FoundationPile(funpile);
        funpile2.setI(12);
        this.funpile = new int[]{3, 6, 9, 12, 2, 5, 8, 11, 1, 4, 7, 10, 13};
        funpile3=new FoundationPile(funpile);
        funpile3.setI(12);
        this.funpile = new int[]{4, 8, 12, 3, 7, 11, 2, 6, 10, 1, 5, 9, 13};
        funpile4=new FoundationPile(funpile);
        funpile4.setI(12);
        
        Card winCard = new Card(Suit.Spades, 13, true);
        wastePile1 = new WastePile();
        wastePile1.push(winCard);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        foundationPile1 = new javax.swing.JLabel();
        wastePileC = new javax.swing.JLabel();
        foundationPile3 = new javax.swing.JLabel();
        wastePileD = new javax.swing.JLabel();
        foundationPile4 = new javax.swing.JLabel();
        wastePileA = new javax.swing.JLabel();
        foundationPile2 = new javax.swing.JLabel();
        wastePileB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        foundationPile1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculation_solitaire/images/Clubs12.png"))); // NOI18N
        foundationPile1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        foundationPile1.setPreferredSize(new java.awt.Dimension(71, 96));
        foundationPile1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                foundationPile1MouseClicked(evt);
            }
        });

        wastePileC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        wastePileC.setPreferredSize(new java.awt.Dimension(71, 96));

        foundationPile3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculation_solitaire/images/Diamonds13.png"))); // NOI18N
        foundationPile3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        foundationPile3.setPreferredSize(new java.awt.Dimension(71, 96));

        wastePileD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        wastePileD.setPreferredSize(new java.awt.Dimension(71, 96));

        foundationPile4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculation_solitaire/images/Hearts13.png"))); // NOI18N
        foundationPile4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        foundationPile4.setPreferredSize(new java.awt.Dimension(71, 96));

        wastePileA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculation_solitaire/images/Spades13.png"))); // NOI18N
        wastePileA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        wastePileA.setPreferredSize(new java.awt.Dimension(71, 96));
        wastePileA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wastePileAMouseClicked(evt);
            }
        });

        foundationPile2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculation_solitaire/images/Clubs13.png"))); // NOI18N
        foundationPile2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        foundationPile2.setPreferredSize(new java.awt.Dimension(71, 96));

        wastePileB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        wastePileB.setPreferredSize(new java.awt.Dimension(71, 96));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(wastePileA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foundationPile1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(foundationPile2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wastePileB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(foundationPile3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(foundationPile4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(wastePileC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(wastePileD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(300, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foundationPile1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foundationPile2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foundationPile3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foundationPile4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wastePileA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wastePileB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wastePileC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wastePileD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wastePileAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wastePileAMouseClicked
        pCard = wastePile1.peek();
        isSelected = true;
        wastePileA.setBorder(BorderFactory.createLineBorder(Color.BLUE, 2));       
    }//GEN-LAST:event_wastePileAMouseClicked

    private void foundationPile1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foundationPile1MouseClicked
        if (isSelected) {
            if(this.funpile1.validFoundation(pCard.getValue())){
                        pCard.setFaceUp(true);
                        foundationPile1.setIcon(pCard.getIcon());
                        pCard.setFaceUp(false);
                        Card ouCard = wastePile1.pop();
                        Card outCard = wastePile1.peek();     
                        if(outCard!=null){
                            wastePileA.setIcon(outCard.getIcon());     
                        }else{
                            wastePileA.setIcon(null);
                        }
                        isSelected = false;   
                        wastePileA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))); 
                        pCard = new Card();
                        System.out.println("Moving card from wastepile1 to foundationPile1");
                        checkWinCon();           
            }
        }
    }//GEN-LAST:event_foundationPile1MouseClicked

    private void checkWinCon(){
        if (funpile1.isFull() && funpile2.isFull() && funpile3.isFull() && funpile4.isFull()) {
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new WinGame().setVisible(true);
                }
            });
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WinTest().setVisible(true);
            }
        });
    }
    private boolean isSelected; 
    private Card pCard;
    private final WastePile wastePile1;
    private int[] funpile;
    private final FoundationPile funpile1;
    private final FoundationPile funpile2;
    private final FoundationPile funpile3;
    private final FoundationPile funpile4;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel foundationPile1;
    private javax.swing.JLabel foundationPile2;
    private javax.swing.JLabel foundationPile3;
    private javax.swing.JLabel foundationPile4;
    private javax.swing.JLabel wastePileA;
    private javax.swing.JLabel wastePileB;
    private javax.swing.JLabel wastePileC;
    private javax.swing.JLabel wastePileD;
    // End of variables declaration//GEN-END:variables
}
